version: '3.8'

services:
  gateway:
    build:
      dockerfile: ./Dockerfile.gateway
    image: scalable.azurecr.io/gateway
    ports:
      - "3000:3000"
    depends_on:
      - user
    environment:
      - NODE_ENV=production

  user:
    build:
      dockerfile: ./Dockerfile.user
    image: scalable.azurecr.io/user
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  meeting:
    build:
      dockerfile: ./Dockerfile.meeting
    image: scalable.azurecr.io/meeting
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production

  server:
    build:
      dockerfile: ./Dockerfile.main
    image: scalable.azurecr.io/main
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production


