version: '3.8'

services:
  gateway:
    build:
      dockerfile: ./backend/gateway/Dockerfile
      context: .
    image: scalable.azurecr.io/gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  
  meetings:
    build:
      dockerfile: ./backend/meetings/Dockerfile
      context: .
    image: scalable.azurecr.io/meetings
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production

  users:
    build:
      dockerfile: ./backend/users/Dockerfile
      context: .
    image: scalable.azurecr.io/users
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
