FROM node:latest

# Set the working directory
WORKDIR /Vafan

# Copy the application code
COPY . .

# Install dependencies
RUN npm install

# Build the React app
RUN npm run build

# Expose the port that the backend is running on
ENV PORT=3003
EXPOSE 3003

# Start the application
CMD node ./src/Server/meeting/server.js