FROM node:latest


# Set the working directory
WORKDIR /Vafan

# Debugging: List files before and after copy
RUN ls -al

# Copy the application code
COPY . .


# Debugging: List files before and after copy
RUN ls -al

# Install dependencies
RUN npm install

# Build the React app
RUN npm run build

# Expose the port that the backend is running on
ENV PORT=3002
EXPOSE 3002

# Start the application
CMD node ./src/Server/userService/server.js