apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-nginx
spec:
  selector:
    matchLabels:
      app: proxy-nginx
  template:
    metadata:
      labels:
        app: proxy-nginx
    spec:
      containers:
        - name: proxy-nginx
          image: $CONTAINER_REGISTRY_LOGIN_SERVER/nginx-proxy:$VERSION
          ports:
          - containerPort: 80
          