apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-microservice
  template:
    metadata:
      labels:
        app: gateway-microservice
    spec:
      containers:
        - name: gateway-microservice-container
          image: $CONTAINER_REGISTRY_LOGIN_SERVER/gateway:$VERSION
          ports:
            - containerPort: 3001

        startupProbe:
            exec:
              command:
              - cat
              - /tmp/started
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 5

          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
