apiVersion: v1
kind: Service
metadata:
  name: gateway-microservice
spec:
  selector:
    app: gateway-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
