name: gateway-cicd

on:
  push:
    branches:
      - main
    paths: 
      - 'backend/gateway/**'
      
jobs:
  gateway-cicd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Sets up environment variables for the job
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY_LOGIN_SERVER: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installs the Node.js package
      - uses: actions/setup-node@v3
        with:
          node-version: 19.9.0
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json' # Path to package-lock.json in video-storage subfolder.
        
      - name: Build docker image
        run : docker build -t $CONTAINER_REGISTRY_LOGIN_SERVER/gateway:$VERSION --file ./Dockerfile .
      
      - name: Push docker image 
        run: |
          echo $CONTAINER_REGISTRY_PASSWORD | docker login $CONTAINER_REGISTRY_LOGIN_SERVER --username $CONTAINER_REGISTRY_USERNAME --password-stdin
          docker push $CONTAINER_REGISTRY_LOGIN_SERVER/gateway:$VERSION

      - run: echo ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} | docker login ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password-stdin 

      #- name: Push images to azure container registry
      #  run: docker-compose push

      - name: echo
        run: echo ${{ secrets.KUBE_CONFIG }}

      - uses: tale/kubectl-action@v1
        with: 
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2
      
      - name: Deploy all kubernetes services and deployments
        run: kubectl apply -f gateway-deployment.yaml && kubectl apply -f gateway-service.yaml 
             


