apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meeting-microservice
  template:
    metadata:
      labels:
        app: meeting-microservice
    spec:
      containers:
        - name: meeting-microservice-container
          image: $CONTAINER_REGISTRY_LOGIN_SERVER/meetings:$VERSION
          ports:
            - containerPort: 3003

          startupProbe:
            exec:
              command:
              - cat
              - /tmp/started
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 5

          readinessProbe:
            tcpSocket:
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3003
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3

