name: nginx-proxy-cicd

on:
  push:
    branches:
      - main
    paths: 
      - 'proxy/**'

  workflow_dispatch:
      
jobs:
  nginx-proxy-cicd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Sets up environment variables for the job
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY_LOGIN_SERVER: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Build docker image
      - name: Build docker image
        run : docker build -t $CONTAINER_REGISTRY_LOGIN_SERVER/nginx-proxy:$VERSION --file ./proxy/Dockerfile .
      
      # Push docker image to container registry
      - name: Push docker image 
        run: |
          echo $CONTAINER_REGISTRY_PASSWORD | docker login $CONTAINER_REGISTRY_LOGIN_SERVER --username $CONTAINER_REGISTRY_USERNAME --password-stdin
          docker push $CONTAINER_REGISTRY_LOGIN_SERVER/nginx-proxy:$VERSION

      # Install and setup kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      # Deploy to kubernetes
      - name: Deploy
        run: | 
          envsubst < proxy/kubernetes/deploy.yaml | kubectl apply -f -
          envsubst < proxy/kubernetes/scaling.yaml | kubectl apply -f -
          envsubst < proxy/kubernetes/service.yaml | kubectl apply -f -
